// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: proto/bidder/bidder.proto

package bidderpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BidderService_EvaluateBid_FullMethodName = "/bidder.BidderService/EvaluateBid"
)

// BidderServiceClient is the client API for BidderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BidderServiceClient interface {
	EvaluateBid(ctx context.Context, in *BidRequest, opts ...grpc.CallOption) (*BidResponse, error)
}

type bidderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBidderServiceClient(cc grpc.ClientConnInterface) BidderServiceClient {
	return &bidderServiceClient{cc}
}

func (c *bidderServiceClient) EvaluateBid(ctx context.Context, in *BidRequest, opts ...grpc.CallOption) (*BidResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BidResponse)
	err := c.cc.Invoke(ctx, BidderService_EvaluateBid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BidderServiceServer is the server API for BidderService service.
// All implementations must embed UnimplementedBidderServiceServer
// for forward compatibility.
type BidderServiceServer interface {
	EvaluateBid(context.Context, *BidRequest) (*BidResponse, error)
	mustEmbedUnimplementedBidderServiceServer()
}

// UnimplementedBidderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBidderServiceServer struct{}

func (UnimplementedBidderServiceServer) EvaluateBid(context.Context, *BidRequest) (*BidResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EvaluateBid not implemented")
}
func (UnimplementedBidderServiceServer) mustEmbedUnimplementedBidderServiceServer() {}
func (UnimplementedBidderServiceServer) testEmbeddedByValue()                       {}

// UnsafeBidderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BidderServiceServer will
// result in compilation errors.
type UnsafeBidderServiceServer interface {
	mustEmbedUnimplementedBidderServiceServer()
}

func RegisterBidderServiceServer(s grpc.ServiceRegistrar, srv BidderServiceServer) {
	// If the following call panics, it indicates UnimplementedBidderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BidderService_ServiceDesc, srv)
}

func _BidderService_EvaluateBid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BidderServiceServer).EvaluateBid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BidderService_EvaluateBid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BidderServiceServer).EvaluateBid(ctx, req.(*BidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BidderService_ServiceDesc is the grpc.ServiceDesc for BidderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BidderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bidder.BidderService",
	HandlerType: (*BidderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EvaluateBid",
			Handler:    _BidderService_EvaluateBid_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/bidder/bidder.proto",
}
