// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/bidder/bidder.proto

package bidderpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Geo           string                 `protobuf:"bytes,2,opt,name=geo,proto3" json:"geo,omitempty"`
	Device        string                 `protobuf:"bytes,3,opt,name=device,proto3" json:"device,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidRequest) Reset() {
	*x = BidRequest{}
	mi := &file_proto_bidder_bidder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidRequest) ProtoMessage() {}

func (x *BidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bidder_bidder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidRequest.ProtoReflect.Descriptor instead.
func (*BidRequest) Descriptor() ([]byte, []int) {
	return file_proto_bidder_bidder_proto_rawDescGZIP(), []int{0}
}

func (x *BidRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *BidRequest) GetGeo() string {
	if x != nil {
		return x.Geo
	}
	return ""
}

func (x *BidRequest) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *BidRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type BidResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	HasBid            bool                   `protobuf:"varint,1,opt,name=has_bid,json=hasBid,proto3" json:"has_bid,omitempty"`
	WinningCampaignId string                 `protobuf:"bytes,2,opt,name=winning_campaign_id,json=winningCampaignId,proto3" json:"winning_campaign_id,omitempty"`
	PriceCents        int64                  `protobuf:"varint,3,opt,name=price_cents,json=priceCents,proto3" json:"price_cents,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BidResponse) Reset() {
	*x = BidResponse{}
	mi := &file_proto_bidder_bidder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidResponse) ProtoMessage() {}

func (x *BidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bidder_bidder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidResponse.ProtoReflect.Descriptor instead.
func (*BidResponse) Descriptor() ([]byte, []int) {
	return file_proto_bidder_bidder_proto_rawDescGZIP(), []int{1}
}

func (x *BidResponse) GetHasBid() bool {
	if x != nil {
		return x.HasBid
	}
	return false
}

func (x *BidResponse) GetWinningCampaignId() string {
	if x != nil {
		return x.WinningCampaignId
	}
	return ""
}

func (x *BidResponse) GetPriceCents() int64 {
	if x != nil {
		return x.PriceCents
	}
	return 0
}

var File_proto_bidder_bidder_proto protoreflect.FileDescriptor

const file_proto_bidder_bidder_proto_rawDesc = "" +
	"\n" +
	"\x19proto/bidder/bidder.proto\x12\x06bidder\"q\n" +
	"\n" +
	"BidRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x10\n" +
	"\x03geo\x18\x02 \x01(\tR\x03geo\x12\x16\n" +
	"\x06device\x18\x03 \x01(\tR\x06device\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\"w\n" +
	"\vBidResponse\x12\x17\n" +
	"\ahas_bid\x18\x01 \x01(\bR\x06hasBid\x12.\n" +
	"\x13winning_campaign_id\x18\x02 \x01(\tR\x11winningCampaignId\x12\x1f\n" +
	"\vprice_cents\x18\x03 \x01(\x03R\n" +
	"priceCents2G\n" +
	"\rBidderService\x126\n" +
	"\vEvaluateBid\x12\x12.bidder.BidRequest\x1a\x13.bidder.BidResponseB?Z=github.com/Gvinay90/ad-bidding-platform/proto/bidder;bidderpbb\x06proto3"

var (
	file_proto_bidder_bidder_proto_rawDescOnce sync.Once
	file_proto_bidder_bidder_proto_rawDescData []byte
)

func file_proto_bidder_bidder_proto_rawDescGZIP() []byte {
	file_proto_bidder_bidder_proto_rawDescOnce.Do(func() {
		file_proto_bidder_bidder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_bidder_bidder_proto_rawDesc), len(file_proto_bidder_bidder_proto_rawDesc)))
	})
	return file_proto_bidder_bidder_proto_rawDescData
}

var file_proto_bidder_bidder_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_bidder_bidder_proto_goTypes = []any{
	(*BidRequest)(nil),  // 0: bidder.BidRequest
	(*BidResponse)(nil), // 1: bidder.BidResponse
}
var file_proto_bidder_bidder_proto_depIdxs = []int32{
	0, // 0: bidder.BidderService.EvaluateBid:input_type -> bidder.BidRequest
	1, // 1: bidder.BidderService.EvaluateBid:output_type -> bidder.BidResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_bidder_bidder_proto_init() }
func file_proto_bidder_bidder_proto_init() {
	if File_proto_bidder_bidder_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_bidder_bidder_proto_rawDesc), len(file_proto_bidder_bidder_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_bidder_bidder_proto_goTypes,
		DependencyIndexes: file_proto_bidder_bidder_proto_depIdxs,
		MessageInfos:      file_proto_bidder_bidder_proto_msgTypes,
	}.Build()
	File_proto_bidder_bidder_proto = out.File
	file_proto_bidder_bidder_proto_goTypes = nil
	file_proto_bidder_bidder_proto_depIdxs = nil
}
