// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/analytics/analytics.proto

package analyticspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CampaignStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    string                 `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CampaignStatsRequest) Reset() {
	*x = CampaignStatsRequest{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CampaignStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CampaignStatsRequest) ProtoMessage() {}

func (x *CampaignStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CampaignStatsRequest.ProtoReflect.Descriptor instead.
func (*CampaignStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *CampaignStatsRequest) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

type CampaignStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    string                 `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	Wins          int64                  `protobuf:"varint,2,opt,name=wins,proto3" json:"wins,omitempty"`
	Bids          int64                  `protobuf:"varint,3,opt,name=bids,proto3" json:"bids,omitempty"`
	SpendCents    int64                  `protobuf:"varint,4,opt,name=spend_cents,json=spendCents,proto3" json:"spend_cents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CampaignStatsResponse) Reset() {
	*x = CampaignStatsResponse{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CampaignStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CampaignStatsResponse) ProtoMessage() {}

func (x *CampaignStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CampaignStatsResponse.ProtoReflect.Descriptor instead.
func (*CampaignStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *CampaignStatsResponse) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *CampaignStatsResponse) GetWins() int64 {
	if x != nil {
		return x.Wins
	}
	return 0
}

func (x *CampaignStatsResponse) GetBids() int64 {
	if x != nil {
		return x.Bids
	}
	return 0
}

func (x *CampaignStatsResponse) GetSpendCents() int64 {
	if x != nil {
		return x.SpendCents
	}
	return 0
}

var File_proto_analytics_analytics_proto protoreflect.FileDescriptor

const file_proto_analytics_analytics_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/analytics/analytics.proto\x12\tanalytics\"7\n" +
	"\x14CampaignStatsRequest\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\tR\n" +
	"campaignId\"\x81\x01\n" +
	"\x15CampaignStatsResponse\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\tR\n" +
	"campaignId\x12\x12\n" +
	"\x04wins\x18\x02 \x01(\x03R\x04wins\x12\x12\n" +
	"\x04bids\x18\x03 \x01(\x03R\x04bids\x12\x1f\n" +
	"\vspend_cents\x18\x04 \x01(\x03R\n" +
	"spendCents2i\n" +
	"\x10AnalyticsService\x12U\n" +
	"\x10GetCampaignStats\x12\x1f.analytics.CampaignStatsRequest\x1a .analytics.CampaignStatsResponseBEZCgithub.com/Gvinay90/ad-bidding-platform/proto/analytics;analyticspbb\x06proto3"

var (
	file_proto_analytics_analytics_proto_rawDescOnce sync.Once
	file_proto_analytics_analytics_proto_rawDescData []byte
)

func file_proto_analytics_analytics_proto_rawDescGZIP() []byte {
	file_proto_analytics_analytics_proto_rawDescOnce.Do(func() {
		file_proto_analytics_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_analytics_analytics_proto_rawDesc), len(file_proto_analytics_analytics_proto_rawDesc)))
	})
	return file_proto_analytics_analytics_proto_rawDescData
}

var file_proto_analytics_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_analytics_analytics_proto_goTypes = []any{
	(*CampaignStatsRequest)(nil),  // 0: analytics.CampaignStatsRequest
	(*CampaignStatsResponse)(nil), // 1: analytics.CampaignStatsResponse
}
var file_proto_analytics_analytics_proto_depIdxs = []int32{
	0, // 0: analytics.AnalyticsService.GetCampaignStats:input_type -> analytics.CampaignStatsRequest
	1, // 1: analytics.AnalyticsService.GetCampaignStats:output_type -> analytics.CampaignStatsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_analytics_analytics_proto_init() }
func file_proto_analytics_analytics_proto_init() {
	if File_proto_analytics_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_analytics_analytics_proto_rawDesc), len(file_proto_analytics_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_analytics_analytics_proto_goTypes,
		DependencyIndexes: file_proto_analytics_analytics_proto_depIdxs,
		MessageInfos:      file_proto_analytics_analytics_proto_msgTypes,
	}.Build()
	File_proto_analytics_analytics_proto = out.File
	file_proto_analytics_analytics_proto_goTypes = nil
	file_proto_analytics_analytics_proto_depIdxs = nil
}
