// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/campaign/campaign.proto

package campaignpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Campaign struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AdvertiserId  string                 `protobuf:"bytes,2,opt,name=advertiser_id,json=advertiserId,proto3" json:"advertiser_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	BudgetCents   int64                  `protobuf:"varint,4,opt,name=budget_cents,json=budgetCents,proto3" json:"budget_cents,omitempty"`
	BidPriceCents int64                  `protobuf:"varint,5,opt,name=bid_price_cents,json=bidPriceCents,proto3" json:"bid_price_cents,omitempty"`
	Geo           string                 `protobuf:"bytes,6,opt,name=geo,proto3" json:"geo,omitempty"`
	Device        string                 `protobuf:"bytes,7,opt,name=device,proto3" json:"device,omitempty"`
	Category      string                 `protobuf:"bytes,8,opt,name=category,proto3" json:"category,omitempty"`
	Status        string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Campaign) Reset() {
	*x = Campaign{}
	mi := &file_proto_campaign_campaign_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Campaign) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Campaign) ProtoMessage() {}

func (x *Campaign) ProtoReflect() protoreflect.Message {
	mi := &file_proto_campaign_campaign_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Campaign.ProtoReflect.Descriptor instead.
func (*Campaign) Descriptor() ([]byte, []int) {
	return file_proto_campaign_campaign_proto_rawDescGZIP(), []int{0}
}

func (x *Campaign) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Campaign) GetAdvertiserId() string {
	if x != nil {
		return x.AdvertiserId
	}
	return ""
}

func (x *Campaign) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Campaign) GetBudgetCents() int64 {
	if x != nil {
		return x.BudgetCents
	}
	return 0
}

func (x *Campaign) GetBidPriceCents() int64 {
	if x != nil {
		return x.BidPriceCents
	}
	return 0
}

func (x *Campaign) GetGeo() string {
	if x != nil {
		return x.Geo
	}
	return ""
}

func (x *Campaign) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *Campaign) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Campaign) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateCampaignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdvertiserId  string                 `protobuf:"bytes,1,opt,name=advertiser_id,json=advertiserId,proto3" json:"advertiser_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	BudgetCents   int64                  `protobuf:"varint,3,opt,name=budget_cents,json=budgetCents,proto3" json:"budget_cents,omitempty"`
	BidPriceCents int64                  `protobuf:"varint,4,opt,name=bid_price_cents,json=bidPriceCents,proto3" json:"bid_price_cents,omitempty"`
	Geo           string                 `protobuf:"bytes,5,opt,name=geo,proto3" json:"geo,omitempty"`
	Device        string                 `protobuf:"bytes,6,opt,name=device,proto3" json:"device,omitempty"`
	Category      string                 `protobuf:"bytes,7,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCampaignRequest) Reset() {
	*x = CreateCampaignRequest{}
	mi := &file_proto_campaign_campaign_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCampaignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCampaignRequest) ProtoMessage() {}

func (x *CreateCampaignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_campaign_campaign_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCampaignRequest.ProtoReflect.Descriptor instead.
func (*CreateCampaignRequest) Descriptor() ([]byte, []int) {
	return file_proto_campaign_campaign_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCampaignRequest) GetAdvertiserId() string {
	if x != nil {
		return x.AdvertiserId
	}
	return ""
}

func (x *CreateCampaignRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCampaignRequest) GetBudgetCents() int64 {
	if x != nil {
		return x.BudgetCents
	}
	return 0
}

func (x *CreateCampaignRequest) GetBidPriceCents() int64 {
	if x != nil {
		return x.BidPriceCents
	}
	return 0
}

func (x *CreateCampaignRequest) GetGeo() string {
	if x != nil {
		return x.Geo
	}
	return ""
}

func (x *CreateCampaignRequest) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *CreateCampaignRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type CampaignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Campaign      *Campaign              `protobuf:"bytes,1,opt,name=campaign,proto3" json:"campaign,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CampaignResponse) Reset() {
	*x = CampaignResponse{}
	mi := &file_proto_campaign_campaign_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CampaignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CampaignResponse) ProtoMessage() {}

func (x *CampaignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_campaign_campaign_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CampaignResponse.ProtoReflect.Descriptor instead.
func (*CampaignResponse) Descriptor() ([]byte, []int) {
	return file_proto_campaign_campaign_proto_rawDescGZIP(), []int{2}
}

func (x *CampaignResponse) GetCampaign() *Campaign {
	if x != nil {
		return x.Campaign
	}
	return nil
}

type GetCampaignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCampaignRequest) Reset() {
	*x = GetCampaignRequest{}
	mi := &file_proto_campaign_campaign_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCampaignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCampaignRequest) ProtoMessage() {}

func (x *GetCampaignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_campaign_campaign_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCampaignRequest.ProtoReflect.Descriptor instead.
func (*GetCampaignRequest) Descriptor() ([]byte, []int) {
	return file_proto_campaign_campaign_proto_rawDescGZIP(), []int{3}
}

func (x *GetCampaignRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListCampaignsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdvertiserId  string                 `protobuf:"bytes,1,opt,name=advertiser_id,json=advertiserId,proto3" json:"advertiser_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCampaignsRequest) Reset() {
	*x = ListCampaignsRequest{}
	mi := &file_proto_campaign_campaign_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCampaignsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCampaignsRequest) ProtoMessage() {}

func (x *ListCampaignsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_campaign_campaign_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCampaignsRequest.ProtoReflect.Descriptor instead.
func (*ListCampaignsRequest) Descriptor() ([]byte, []int) {
	return file_proto_campaign_campaign_proto_rawDescGZIP(), []int{4}
}

func (x *ListCampaignsRequest) GetAdvertiserId() string {
	if x != nil {
		return x.AdvertiserId
	}
	return ""
}

type ListCampaignsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Campaigns     []*Campaign            `protobuf:"bytes,1,rep,name=campaigns,proto3" json:"campaigns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCampaignsResponse) Reset() {
	*x = ListCampaignsResponse{}
	mi := &file_proto_campaign_campaign_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCampaignsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCampaignsResponse) ProtoMessage() {}

func (x *ListCampaignsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_campaign_campaign_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCampaignsResponse.ProtoReflect.Descriptor instead.
func (*ListCampaignsResponse) Descriptor() ([]byte, []int) {
	return file_proto_campaign_campaign_proto_rawDescGZIP(), []int{5}
}

func (x *ListCampaignsResponse) GetCampaigns() []*Campaign {
	if x != nil {
		return x.Campaigns
	}
	return nil
}

type UpdateCampaignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	BudgetCents   int64                  `protobuf:"varint,3,opt,name=budget_cents,json=budgetCents,proto3" json:"budget_cents,omitempty"`
	BidPriceCents int64                  `protobuf:"varint,4,opt,name=bid_price_cents,json=bidPriceCents,proto3" json:"bid_price_cents,omitempty"`
	Geo           string                 `protobuf:"bytes,5,opt,name=geo,proto3" json:"geo,omitempty"`
	Device        string                 `protobuf:"bytes,6,opt,name=device,proto3" json:"device,omitempty"`
	Category      string                 `protobuf:"bytes,7,opt,name=category,proto3" json:"category,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCampaignRequest) Reset() {
	*x = UpdateCampaignRequest{}
	mi := &file_proto_campaign_campaign_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCampaignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCampaignRequest) ProtoMessage() {}

func (x *UpdateCampaignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_campaign_campaign_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCampaignRequest.ProtoReflect.Descriptor instead.
func (*UpdateCampaignRequest) Descriptor() ([]byte, []int) {
	return file_proto_campaign_campaign_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateCampaignRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCampaignRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCampaignRequest) GetBudgetCents() int64 {
	if x != nil {
		return x.BudgetCents
	}
	return 0
}

func (x *UpdateCampaignRequest) GetBidPriceCents() int64 {
	if x != nil {
		return x.BidPriceCents
	}
	return 0
}

func (x *UpdateCampaignRequest) GetGeo() string {
	if x != nil {
		return x.Geo
	}
	return ""
}

func (x *UpdateCampaignRequest) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *UpdateCampaignRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *UpdateCampaignRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DeleteCampaignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCampaignRequest) Reset() {
	*x = DeleteCampaignRequest{}
	mi := &file_proto_campaign_campaign_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCampaignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCampaignRequest) ProtoMessage() {}

func (x *DeleteCampaignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_campaign_campaign_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCampaignRequest.ProtoReflect.Descriptor instead.
func (*DeleteCampaignRequest) Descriptor() ([]byte, []int) {
	return file_proto_campaign_campaign_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteCampaignRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteCampaignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCampaignResponse) Reset() {
	*x = DeleteCampaignResponse{}
	mi := &file_proto_campaign_campaign_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCampaignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCampaignResponse) ProtoMessage() {}

func (x *DeleteCampaignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_campaign_campaign_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCampaignResponse.ProtoReflect.Descriptor instead.
func (*DeleteCampaignResponse) Descriptor() ([]byte, []int) {
	return file_proto_campaign_campaign_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteCampaignResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_campaign_campaign_proto protoreflect.FileDescriptor

const file_proto_campaign_campaign_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/campaign/campaign.proto\x12\bcampaign\"\xfc\x01\n" +
	"\bCampaign\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\radvertiser_id\x18\x02 \x01(\tR\fadvertiserId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12!\n" +
	"\fbudget_cents\x18\x04 \x01(\x03R\vbudgetCents\x12&\n" +
	"\x0fbid_price_cents\x18\x05 \x01(\x03R\rbidPriceCents\x12\x10\n" +
	"\x03geo\x18\x06 \x01(\tR\x03geo\x12\x16\n" +
	"\x06device\x18\a \x01(\tR\x06device\x12\x1a\n" +
	"\bcategory\x18\b \x01(\tR\bcategory\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\"\xe1\x01\n" +
	"\x15CreateCampaignRequest\x12#\n" +
	"\radvertiser_id\x18\x01 \x01(\tR\fadvertiserId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fbudget_cents\x18\x03 \x01(\x03R\vbudgetCents\x12&\n" +
	"\x0fbid_price_cents\x18\x04 \x01(\x03R\rbidPriceCents\x12\x10\n" +
	"\x03geo\x18\x05 \x01(\tR\x03geo\x12\x16\n" +
	"\x06device\x18\x06 \x01(\tR\x06device\x12\x1a\n" +
	"\bcategory\x18\a \x01(\tR\bcategory\"B\n" +
	"\x10CampaignResponse\x12.\n" +
	"\bcampaign\x18\x01 \x01(\v2\x12.campaign.CampaignR\bcampaign\"$\n" +
	"\x12GetCampaignRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\";\n" +
	"\x14ListCampaignsRequest\x12#\n" +
	"\radvertiser_id\x18\x01 \x01(\tR\fadvertiserId\"I\n" +
	"\x15ListCampaignsResponse\x120\n" +
	"\tcampaigns\x18\x01 \x03(\v2\x12.campaign.CampaignR\tcampaigns\"\xe4\x01\n" +
	"\x15UpdateCampaignRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fbudget_cents\x18\x03 \x01(\x03R\vbudgetCents\x12&\n" +
	"\x0fbid_price_cents\x18\x04 \x01(\x03R\rbidPriceCents\x12\x10\n" +
	"\x03geo\x18\x05 \x01(\tR\x03geo\x12\x16\n" +
	"\x06device\x18\x06 \x01(\tR\x06device\x12\x1a\n" +
	"\bcategory\x18\a \x01(\tR\bcategory\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\"'\n" +
	"\x15DeleteCampaignRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"2\n" +
	"\x16DeleteCampaignResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\x9f\x03\n" +
	"\x0fCampaignService\x12M\n" +
	"\x0eCreateCampaign\x12\x1f.campaign.CreateCampaignRequest\x1a\x1a.campaign.CampaignResponse\x12G\n" +
	"\vGetCampaign\x12\x1c.campaign.GetCampaignRequest\x1a\x1a.campaign.CampaignResponse\x12P\n" +
	"\rListCampaigns\x12\x1e.campaign.ListCampaignsRequest\x1a\x1f.campaign.ListCampaignsResponse\x12M\n" +
	"\x0eUpdateCampaign\x12\x1f.campaign.UpdateCampaignRequest\x1a\x1a.campaign.CampaignResponse\x12S\n" +
	"\x0eDeleteCampaign\x12\x1f.campaign.DeleteCampaignRequest\x1a .campaign.DeleteCampaignResponseBCZAgithub.com/Gvinay90/ad-bidding-platform/proto/campaign;campaignpbb\x06proto3"

var (
	file_proto_campaign_campaign_proto_rawDescOnce sync.Once
	file_proto_campaign_campaign_proto_rawDescData []byte
)

func file_proto_campaign_campaign_proto_rawDescGZIP() []byte {
	file_proto_campaign_campaign_proto_rawDescOnce.Do(func() {
		file_proto_campaign_campaign_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_campaign_campaign_proto_rawDesc), len(file_proto_campaign_campaign_proto_rawDesc)))
	})
	return file_proto_campaign_campaign_proto_rawDescData
}

var file_proto_campaign_campaign_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_campaign_campaign_proto_goTypes = []any{
	(*Campaign)(nil),               // 0: campaign.Campaign
	(*CreateCampaignRequest)(nil),  // 1: campaign.CreateCampaignRequest
	(*CampaignResponse)(nil),       // 2: campaign.CampaignResponse
	(*GetCampaignRequest)(nil),     // 3: campaign.GetCampaignRequest
	(*ListCampaignsRequest)(nil),   // 4: campaign.ListCampaignsRequest
	(*ListCampaignsResponse)(nil),  // 5: campaign.ListCampaignsResponse
	(*UpdateCampaignRequest)(nil),  // 6: campaign.UpdateCampaignRequest
	(*DeleteCampaignRequest)(nil),  // 7: campaign.DeleteCampaignRequest
	(*DeleteCampaignResponse)(nil), // 8: campaign.DeleteCampaignResponse
}
var file_proto_campaign_campaign_proto_depIdxs = []int32{
	0, // 0: campaign.CampaignResponse.campaign:type_name -> campaign.Campaign
	0, // 1: campaign.ListCampaignsResponse.campaigns:type_name -> campaign.Campaign
	1, // 2: campaign.CampaignService.CreateCampaign:input_type -> campaign.CreateCampaignRequest
	3, // 3: campaign.CampaignService.GetCampaign:input_type -> campaign.GetCampaignRequest
	4, // 4: campaign.CampaignService.ListCampaigns:input_type -> campaign.ListCampaignsRequest
	6, // 5: campaign.CampaignService.UpdateCampaign:input_type -> campaign.UpdateCampaignRequest
	7, // 6: campaign.CampaignService.DeleteCampaign:input_type -> campaign.DeleteCampaignRequest
	2, // 7: campaign.CampaignService.CreateCampaign:output_type -> campaign.CampaignResponse
	2, // 8: campaign.CampaignService.GetCampaign:output_type -> campaign.CampaignResponse
	5, // 9: campaign.CampaignService.ListCampaigns:output_type -> campaign.ListCampaignsResponse
	2, // 10: campaign.CampaignService.UpdateCampaign:output_type -> campaign.CampaignResponse
	8, // 11: campaign.CampaignService.DeleteCampaign:output_type -> campaign.DeleteCampaignResponse
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_campaign_campaign_proto_init() }
func file_proto_campaign_campaign_proto_init() {
	if File_proto_campaign_campaign_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_campaign_campaign_proto_rawDesc), len(file_proto_campaign_campaign_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_campaign_campaign_proto_goTypes,
		DependencyIndexes: file_proto_campaign_campaign_proto_depIdxs,
		MessageInfos:      file_proto_campaign_campaign_proto_msgTypes,
	}.Build()
	File_proto_campaign_campaign_proto = out.File
	file_proto_campaign_campaign_proto_goTypes = nil
	file_proto_campaign_campaign_proto_depIdxs = nil
}
